import type { ThemeDefinition } from '../types';

// Arcane Light — "Vellum & Iron-Gall Ink".
// Fully light (no dark titlebar) — vellum canvas, deep sepia ink, balanced
// sienna accent like a rubricated capital in an illuminated manuscript.
// Iron-rust reserved for errors / JSX tags / dirty-state, deep moss for
// strings and added-lines. Different personality from Arcane Dark, not an
// inverted-lightness flip.
const arcaneLight: ThemeDefinition = {
  id: 'arcane-light',
  name: 'Arcane Light',
  type: 'light',
  ui: {
    'bg-primary': '#FAF7F0',
    'bg-sidebar': '#F2EDE0',
    'bg-titlebar': '#EFE9DA',
    'bg-tab-active': '#FCFAF3',
    'bg-tab-inactive': '#F2EDE0',
    'bg-statusbar': '#EFE9DA',
    'bg-activity-bar': '#EFE9DA',
    'bg-breadcrumbs': '#FAF7F0',
    'bg-input': '#FCFAF3',
    'text-primary': '#2A2622',
    'text-secondary': '#6B6358',
    'text-active': '#1A1612',
    'text-breadcrumb': '#857C6E',
    'text-breadcrumb-active': '#2A2622',
    'text-on-dark': '#2A2622',
    'border': 'rgba(42, 38, 34, 0.08)',
    'accent': '#A8632A',
    'accent-secondary': '#7A4318',
    'hover': 'rgba(42, 38, 34, 0.04)',
    'selected': 'rgba(168, 99, 42, 0.10)',
    'git-modified': '#9E7A1C',
    'git-added': '#4F6B3A',
    'git-deleted': '#9E3A2C',
    'git-untracked': '#4F6B3A',
    'overlay-shadow': 'rgba(42, 38, 34, 0.18)',
    'badge-bg': 'rgba(168, 99, 42, 0.14)',
    'hover-overlay': 'rgba(42, 38, 34, 0.04)',
    'statusbar-hover': 'rgba(42, 38, 34, 0.05)',
    'error-bg': 'rgba(158, 58, 44, 0.08)',
    'error-border': '#9E3A2C',
    'error-text': '#9E3A2C',
    'editor-error-btn': '#9E3A2C',
    'editor-error-btn-hover': '#7A2A1E',
    'folder-icon': '#857C6E',
    'surface-container-high': '#F2EDE0',
    'surface-container-highest': '#EFE9DA',
    'surface-bright': '#FCFAF3',
    'primary-light': '#7A4318',
    'ghost-border': 'rgba(168, 99, 42, 0.20)',
    'warning': '#9E7A1C',
    'warning-bg': 'rgba(158, 122, 28, 0.10)',
    'info': '#3A6680',
    'info-bg': 'rgba(58, 102, 128, 0.08)',
    'success': '#4F6B3A',
    'modal-backdrop': 'rgba(42, 38, 34, 0.30)',
    'modal-shadow': '0 8px 32px rgba(42, 38, 34, 0.12), 0 0 0 1px rgba(42, 38, 34, 0.06)',
    'scrollbar-thumb': 'rgba(42, 38, 34, 0.16)',
    'scrollbar-thumb-hover': 'rgba(42, 38, 34, 0.28)',
    'focus-ring': 'rgba(168, 99, 42, 0.45)',
    'button-primary-bg': '#A8632A',
    'button-primary-text': '#FCFAF3',
    'button-primary-hover': '#7A4318',
    'button-danger-bg': '#9E3A2C',
    'button-danger-text': '#FCFAF3',
    'avatar-gradient-start': '#A8632A',
    'avatar-gradient-end': '#6B3410',
    'avatar-text': '#FCFAF3',
  },
  monaco: {
    base: 'vs',
    inherit: true,
    rules: [
      // --- Original 16 rules ---
      { token: 'comment', foreground: 'A09584', fontStyle: 'italic' },
      { token: 'keyword', foreground: '7A4318' },
      { token: 'string', foreground: '4F6B3A' },
      { token: 'number', foreground: '7A4318' },
      { token: 'type', foreground: '3A6680' },
      { token: 'function', foreground: 'A8632A' },
      { token: 'variable', foreground: '2A2622' },
      { token: 'constant', foreground: '7A4318' },
      { token: 'parameter', foreground: '5C5448' },
      { token: 'property', foreground: '3A6680' },
      { token: 'tag', foreground: '9E3A2C' },
      { token: 'attribute.name', foreground: 'A8632A' },
      { token: 'attribute.value', foreground: '4F6B3A' },
      { token: 'delimiter', foreground: '6B6358' },
      { token: 'operator', foreground: '7A4318' },
      { token: 'regexp', foreground: '4F6B3A' },

      // --- Keywords & Storage ---
      { token: 'keyword.control', foreground: '7A4318', fontStyle: 'italic' },
      { token: 'keyword.operator.new', foreground: '7A4318' },
      { token: 'keyword.operator.expression', foreground: '7A4318' },
      { token: 'storage', foreground: '7A4318' },
      { token: 'storage.type', foreground: '3A6680' },
      { token: 'storage.modifier', foreground: '7A4318' },

      // --- Variables & Constants ---
      { token: 'variable.language', foreground: '9E3A2C', fontStyle: 'italic' },
      { token: 'variable.other.constant', foreground: '7A4318' },
      { token: 'constant.language', foreground: '7A4318' },

      // --- Entities & Support ---
      { token: 'entity.name.function', foreground: 'A8632A' },
      { token: 'entity.name.class', foreground: '3A6680' },
      { token: 'entity.name.type', foreground: '3A6680' },
      { token: 'support.function', foreground: 'A8632A' },
      { token: 'support.class', foreground: '3A6680' },
      { token: 'support.type', foreground: '3A6680' },

      // --- JSX/TSX ---
      { token: 'entity.name.tag', foreground: '9E3A2C' },
      { token: 'support.class.component', foreground: '3A6680' },

      // --- Punctuation & Delimiters ---
      { token: 'meta.brace.round', foreground: '6B6358' },
      { token: 'meta.brace.square', foreground: '6B6358' },
      { token: 'meta.brace.curly', foreground: 'A8632A' },
      { token: 'punctuation.separator', foreground: '6B6358' },
      { token: 'string.template', foreground: '4F6B3A' },
      { token: 'punctuation.definition.template-expression', foreground: '7A4318' },

      // --- Decorators ---
      { token: 'meta.decorator', foreground: '9E3A2C' },
    ],
    colors: {
      'editor.background': '#FAF7F0',
      'editor.foreground': '#2A2622',
      'editorCursor.foreground': '#A8632A',
      'editor.lineHighlightBackground': '#F2EDE0',
      'editor.lineHighlightBorder': '#F2EDE0',
      'editor.selectionBackground': 'rgba(168, 99, 42, 0.15)',
      'editor.selectionHighlightBackground': 'rgba(168, 99, 42, 0.10)',
      'editor.wordHighlightBackground': 'rgba(168, 99, 42, 0.08)',
      'editor.findMatchBackground': 'rgba(168, 99, 42, 0.25)',
      'editor.findMatchHighlightBackground': 'rgba(168, 99, 42, 0.12)',
      'editorLineNumber.foreground': '#C5BDAE',
      'editorLineNumber.activeForeground': '#A8632A',
      'editorIndentGuide.background': '#E5DECD',
      'editorIndentGuide.activeBackground': '#C5BDAE',
      'editorWidget.background': '#FCFAF3',
      'editorWidget.foreground': '#2A2622',
      'editorWidget.border': '#E5DECD',
      'editorSuggestWidget.background': '#FCFAF3',
      'editorSuggestWidget.border': '#E5DECD',
      'editorSuggestWidget.selectedBackground': 'rgba(168, 99, 42, 0.12)',
      'editorHoverWidget.background': '#FCFAF3',
      'editorHoverWidget.border': '#E5DECD',
      'editorBracketMatch.background': 'rgba(168, 99, 42, 0.12)',
      'editorBracketMatch.border': '#A8632A',
      'editorGutter.background': '#FAF7F0',
      'editorGutter.modifiedBackground': '#9E7A1C',
      'editorGutter.addedBackground': '#4F6B3A',
      'editorGutter.deletedBackground': '#9E3A2C',
      'scrollbarSlider.background': 'rgba(42, 38, 34, 0.10)',
      'scrollbarSlider.hoverBackground': 'rgba(42, 38, 34, 0.20)',
      'scrollbarSlider.activeBackground': 'rgba(42, 38, 34, 0.30)',
      'minimap.background': '#FAF7F0',
      'minimapSlider.background': 'rgba(42, 38, 34, 0.08)',
      'minimapSlider.hoverBackground': 'rgba(42, 38, 34, 0.18)',
    },
  },
  terminal: {
    background: '#FAF7F0',
    foreground: '#2A2622',
    cursor: '#A8632A',
    cursorAccent: '#FCFAF3',
    selectionBackground: 'rgba(168, 99, 42, 0.20)',
    black: '#2A2622',
    red: '#9E3A2C',
    green: '#4F6B3A',
    yellow: '#9E7A1C',
    blue: '#3A6680',
    magenta: '#7A3A6E',
    cyan: '#3A7080',
    white: '#857C6E',
    brightBlack: '#857C6E',
    brightRed: '#C25940',
    brightGreen: '#6B8A52',
    brightYellow: '#C29A28',
    brightBlue: '#5882A0',
    brightMagenta: '#9C5C8E',
    brightCyan: '#5894A4',
    brightWhite: '#FCFAF3',
  },
};

export default arcaneLight;
