import type { ThemeDefinition } from '../types';

const darkPlus: ThemeDefinition = {
  id: 'dark-plus',
  name: 'Dark+ (Default Dark)',
  type: 'dark',
  ui: {
    'bg-primary': '#1e1e1e',
    'bg-sidebar': '#252526',
    'bg-titlebar': '#323233',
    'bg-tab-active': '#1e1e1e',
    'bg-tab-inactive': '#2d2d2d',
    'bg-statusbar': '#007acc',
    'bg-activity-bar': '#333333',
    'bg-breadcrumbs': '#1e1e1e',
    'bg-input': '#3c3c3c',
    'text-primary': '#cccccc',
    'text-secondary': '#858585',
    'text-active': '#ffffff',
    'text-breadcrumb': '#a0a0a0',
    'text-breadcrumb-active': '#cccccc',
    'text-on-dark': '#ffffff',
    // on #007acc VS Code blue
    'statusbar-fg': '#ffffff',
    'border': '#3c3c3c',
    'accent': '#007acc',
    'accent-secondary': '#3399dd',
    'hover': '#2a2d2e',
    'selected': '#094771',
    'git-modified': '#e2c08d',
    'git-added': '#73c991',
    'git-deleted': '#c74e39',
    'git-untracked': '#73c991',
    'badge-bg': 'rgba(255, 255, 255, 0.1)',
    'hover-overlay': 'rgba(255, 255, 255, 0.1)',
    'statusbar-hover': 'rgba(255, 255, 255, 0.12)',
    'error-bg': 'rgba(204, 51, 51, 0.15)',
    'error-border': '#cc3333',
    'error-text': '#f48771',
    'editor-error-btn': '#0078d4',
    'editor-error-btn-hover': '#1a8ad4',
    'folder-icon': '#dcb67a',
    'surface-container-high': '#3c3c3c',
    'surface-container-highest': '#454545',
    'surface-bright': '#4e4e4e',
    'primary-light': '#3399dd',
    'ghost-border': '#3c3c3c',
    'warning': '#cca700',
    'warning-bg': 'rgba(204, 167, 0, 0.14)',
    'info': '#75beff',
    'info-bg': 'rgba(117, 190, 255, 0.12)',
    'success': '#73c991',
    // Unity semantics, derived from this theme's own warning / info /
    // error-border so no new palette decisions are made on its behalf.
    'unity-lifecycle': '#cca700',
    'unity-engine-type': '#75beff',
    'unity-inspector': '#cc3333',
    'unity-inspector-rail': 'rgba(204, 51, 51, 0.06)',
    'modal-backdrop': 'rgba(0, 0, 0, 0.55)',
    'modal-shadow': '0 8px 24px rgba(0, 0, 0, 0.45)',
    'scrollbar-thumb': 'rgba(255, 255, 255, 0.10)',
    'scrollbar-thumb-hover': 'rgba(255, 255, 255, 0.28)',
    'focus-ring': 'rgba(0, 122, 204, 0.65)',
    'button-primary-bg': '#0e639c',
    'button-primary-text': '#ffffff',
    'button-primary-hover': '#1177bb',
    'button-danger-bg': '#c74e39',
    'button-danger-text': '#ffffff',
    'avatar-gradient-start': '#4a9eff',
    'avatar-gradient-end': '#6366f1',
    'avatar-text': '#ffffff',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      // --- Original 16 rules ---
      { token: 'comment', foreground: '6A9955' },
      { token: 'keyword', foreground: '569CD6' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'type', foreground: '4EC9B0' },
      { token: 'function', foreground: 'DCDCAA' },
      { token: 'variable', foreground: '9CDCFE' },
      { token: 'constant', foreground: '4FC1FF' },
      { token: 'parameter', foreground: '9CDCFE' },
      { token: 'property', foreground: '9CDCFE' },
      { token: 'tag', foreground: '569CD6' },
      { token: 'attribute.name', foreground: '9CDCFE' },
      { token: 'attribute.value', foreground: 'CE9178' },
      { token: 'delimiter', foreground: 'D4D4D4' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'regexp', foreground: 'D16969' },

      // --- Keywords & Storage ---
      { token: 'keyword.control', foreground: 'C586C0' },
      { token: 'keyword.operator.new', foreground: '569CD6' },
      { token: 'keyword.operator.expression', foreground: '569CD6' },
      { token: 'storage', foreground: '569CD6' },
      { token: 'storage.type', foreground: '569CD6' },
      { token: 'storage.modifier', foreground: '569CD6' },

      // --- Variables & Constants ---
      { token: 'variable.language', foreground: '569CD6' },
      { token: 'variable.other.constant', foreground: '4FC1FF' },
      { token: 'constant.language', foreground: '569CD6' },

      // --- Entities & Support ---
      { token: 'entity.name.function', foreground: 'DCDCAA' },
      { token: 'entity.name.class', foreground: '4EC9B0' },
      { token: 'entity.name.type', foreground: '4EC9B0' },
      { token: 'support.function', foreground: 'DCDCAA' },
      { token: 'support.class', foreground: '4EC9B0' },
      { token: 'support.type', foreground: '4EC9B0' },

      // --- JSX/TSX ---
      { token: 'entity.name.tag', foreground: '569CD6' },
      { token: 'support.class.component', foreground: '4EC9B0' },

      // --- Punctuation & Delimiters ---
      { token: 'meta.brace.round', foreground: 'D4D4D4' },
      { token: 'meta.brace.square', foreground: 'D4D4D4' },
      { token: 'meta.brace.curly', foreground: 'D4D4D4' },
      { token: 'punctuation.separator', foreground: 'D4D4D4' },
      { token: 'string.template', foreground: 'CE9178' },
      { token: 'punctuation.definition.template-expression', foreground: '569CD6' },

      // --- Decorators ---
      { token: 'meta.decorator', foreground: 'DCDCAA' },
    ],
    colors: {
      'editor.background': '#1e1e1e',
      'editor.foreground': '#d4d4d4',
      'editorCursor.foreground': '#d4d4d4',
      'editor.lineHighlightBackground': '#2a2d2e',
      'editor.selectionBackground': '#264f78',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#c6c6c6',
      'editorIndentGuide.background': '#404040',
      'editorWidget.background': '#252526',
      'editorWidget.border': '#454545',
    },
  },
  terminal: {
    background: '#1e1e1e',
    foreground: '#d4d4d4',
    cursor: '#d4d4d4',
    cursorAccent: '#1e1e1e',
    selectionBackground: '#264f78',
    black: '#000000',
    red: '#cd3131',
    green: '#0dbc79',
    yellow: '#e5e510',
    blue: '#2472c8',
    magenta: '#bc3fbc',
    cyan: '#11a8cd',
    white: '#e5e5e5',
    brightBlack: '#666666',
    brightRed: '#f14c4c',
    brightGreen: '#23d18b',
    brightYellow: '#f5f543',
    brightBlue: '#3b8eea',
    brightMagenta: '#d670d6',
    brightCyan: '#29b8db',
    brightWhite: '#e5e5e5',
  },
};

export default darkPlus;
