import type { ThemeDefinition } from '../types';

const dracula: ThemeDefinition = {
  id: 'dracula',
  name: 'Dracula',
  type: 'dark',
  ui: {
    'bg-primary': '#282a36',
    'bg-sidebar': '#21222c',
    'bg-titlebar': '#21222c',
    'bg-tab-active': '#282a36',
    'bg-tab-inactive': '#21222c',
    'bg-statusbar': '#191a21',
    'bg-activity-bar': '#343746',
    'bg-breadcrumbs': '#282a36',
    'bg-input': '#44475a',
    'text-primary': '#f8f8f2',
    'text-secondary': '#6272a4',
    'text-active': '#ffffff',
    'text-breadcrumb': '#6272a4',
    'text-breadcrumb-active': '#f8f8f2',
    'text-on-dark': '#f8f8f2',
    // on #191a21 near-black
    'statusbar-fg': '#f8f8f2',
    'border': '#44475a',
    'accent': '#bd93f9',
    'accent-secondary': '#ff79c6',
    // AI composer mode accents (CONTENT class).
    'mode-ask': '#8be9fd',
    'mode-agent': '#bd93f9',
    'mode-plan': '#ffb86c',
    'hover': '#44475a',
    'selected': '#44475a',
    'git-modified': '#8be9fd',
    'git-added': '#50fa7b',
    'git-deleted': '#ff5555',
    'git-untracked': '#50fa7b',
    'badge-bg': 'rgba(255, 255, 255, 0.1)',
    'hover-overlay': 'rgba(255, 255, 255, 0.08)',
    'statusbar-hover': 'rgba(255, 255, 255, 0.12)',
    'error-bg': 'rgba(255, 85, 85, 0.15)',
    'error-border': '#ff5555',
    'error-text': '#ff5555',
    'editor-error-btn': '#bd93f9',
    'editor-error-btn-hover': '#caa8fb',
    'folder-icon': '#f1fa8c',
    'surface-container-high': '#44475a',
    'surface-container-highest': '#4e5166',
    'surface-bright': '#585b72',
    'primary-light': '#d4b1fb',
    'ghost-border': '#44475a',
    'warning': '#f1fa8c',
    'warning-bg': 'rgba(241, 250, 140, 0.12)',
    'info': '#8be9fd',
    'info-bg': 'rgba(139, 233, 253, 0.12)',
    'success': '#50fa7b',
    // Unity semantics, derived from this theme's own warning / info /
    // accent so no new palette decisions are made on its behalf. Inspector is
    // the RAIL colour, not a text colour — see arcane-dark for why.
    'unity-lifecycle': '#f1fa8c',
    'unity-engine-type': '#8be9fd',
    'unity-inspector': '#bd93f9',
    'unity-inspector-rail': 'rgba(189, 147, 249, 0.07)',
    'modal-backdrop': 'rgba(33, 34, 44, 0.65)',
    'modal-shadow': '0 8px 24px rgba(0, 0, 0, 0.55)',
    'scrollbar-thumb': 'rgba(189, 147, 249, 0.20)',
    'scrollbar-thumb-hover': 'rgba(189, 147, 249, 0.45)',
    'focus-ring': 'rgba(189, 147, 249, 0.65)',
    'button-primary-bg': '#bd93f9',
    'button-primary-text': '#282a36',
    'button-primary-hover': '#caa8fb',
    'button-danger-bg': '#ff5555',
    'button-danger-text': '#282a36',
    'avatar-gradient-start': '#bd93f9',
    'avatar-gradient-end': '#ff79c6',
    'avatar-text': '#282a36',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      // --- Original 16 rules ---
      { token: 'comment', foreground: '6272A4', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'FF79C6' },
      { token: 'string', foreground: 'F1FA8C' },
      { token: 'number', foreground: 'BD93F9' },
      { token: 'type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'function', foreground: '50FA7B' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'constant', foreground: 'BD93F9' },
      { token: 'parameter', foreground: 'FFB86C', fontStyle: 'italic' },
      { token: 'property', foreground: 'F8F8F2' },
      { token: 'tag', foreground: 'FF79C6' },
      { token: 'attribute.name', foreground: '50FA7B' },
      { token: 'attribute.value', foreground: 'F1FA8C' },
      { token: 'delimiter', foreground: 'F8F8F2' },
      { token: 'operator', foreground: 'FF79C6' },
      { token: 'regexp', foreground: 'F1FA8C' },

      // --- Keywords & Storage ---
      { token: 'keyword.control', foreground: 'FF79C6' },
      { token: 'keyword.operator.new', foreground: 'FF79C6' },
      { token: 'keyword.operator.expression', foreground: 'FF79C6' },
      { token: 'storage', foreground: 'FF79C6' },
      { token: 'storage.type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'storage.modifier', foreground: 'FF79C6' },

      // --- Variables & Constants ---
      { token: 'variable.language', foreground: 'BD93F9' },
      { token: 'variable.other.constant', foreground: 'BD93F9' },
      { token: 'constant.language', foreground: 'BD93F9' },

      // --- Entities & Support ---
      { token: 'entity.name.function', foreground: '50FA7B' },
      { token: 'entity.name.class', foreground: '8BE9FD' },
      { token: 'entity.name.type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'support.function', foreground: '8BE9FD' },
      { token: 'support.class', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'support.type', foreground: '8BE9FD', fontStyle: 'italic' },

      // --- JSX/TSX ---
      { token: 'entity.name.tag', foreground: 'FF79C6' },
      { token: 'support.class.component', foreground: '50FA7B' },

      // --- Punctuation & Delimiters ---
      { token: 'meta.brace.round', foreground: 'F8F8F2' },
      { token: 'meta.brace.square', foreground: 'F8F8F2' },
      { token: 'meta.brace.curly', foreground: 'F8F8F2' },
      { token: 'punctuation.separator', foreground: 'F8F8F2' },
      { token: 'string.template', foreground: 'F1FA8C' },
      { token: 'punctuation.definition.template-expression', foreground: 'FF79C6' },

      // --- Decorators ---
      { token: 'meta.decorator', foreground: '50FA7B' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editorCursor.foreground': '#f8f8f0',
      'editor.lineHighlightBackground': '#44475a75',
      'editor.selectionBackground': '#44475a',
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#f8f8f2',
      'editorIndentGuide.background': '#424450',
      'editorWidget.background': '#21222c',
      'editorWidget.border': '#44475a',
    },
  },
  terminal: {
    background: '#282a36',
    foreground: '#f8f8f2',
    cursor: '#f8f8f2',
    cursorAccent: '#282a36',
    selectionBackground: '#44475a',
    black: '#21222c',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
    blue: '#bd93f9',
    magenta: '#ff79c6',
    cyan: '#8be9fd',
    white: '#f8f8f2',
    brightBlack: '#6272a4',
    brightRed: '#ff6e6e',
    brightGreen: '#69ff94',
    brightYellow: '#ffffa5',
    brightBlue: '#d6acff',
    brightMagenta: '#ff92df',
    brightCyan: '#a4ffff',
    brightWhite: '#ffffff',
  },
};

export default dracula;
