import type { ThemeDefinition } from '../types';

const lightPlus: ThemeDefinition = {
  id: 'light-plus',
  name: 'Light+ (Default Light)',
  type: 'light',
  ui: {
    'bg-primary': '#ffffff',
    'bg-sidebar': '#f3f3f3',
    'bg-titlebar': '#dddddd',
    'bg-tab-active': '#ffffff',
    'bg-tab-inactive': '#ececec',
    'bg-statusbar': '#007acc',
    'bg-activity-bar': '#2c2c2c',
    'bg-breadcrumbs': '#ffffff',
    'bg-input': '#ffffff',
    'text-primary': '#333333',
    'text-secondary': '#717171',
    'text-active': '#000000',
    'text-breadcrumb': '#717171',
    'text-breadcrumb-active': '#333333',
    'text-on-dark': '#ffffff',
    // on #007acc VS Code blue
    'statusbar-fg': '#ffffff',
    'border': '#e5e5e5',
    'accent': '#007acc',
    'accent-secondary': '#33aadd',
    // AI composer mode accents (CONTENT class).
    'mode-ask': '#316bcd',
    'mode-agent': '#007acc',
    'mode-plan': '#8e44ad',
    'hover': '#e8e8e8',
    'selected': '#cce5ff',
    'git-modified': '#895503',
    'git-added': '#587c0c',
    'git-deleted': '#ad0707',
    'git-untracked': '#587c0c',
    'badge-bg': 'rgba(0, 0, 0, 0.08)',
    'hover-overlay': 'rgba(0, 0, 0, 0.05)',
    'statusbar-hover': 'rgba(255, 255, 255, 0.12)',
    'error-bg': 'rgba(204, 51, 51, 0.1)',
    'error-border': '#cc3333',
    'error-text': '#cc3333',
    'editor-error-btn': '#007acc',
    'editor-error-btn-hover': '#0062a3',
    'folder-icon': '#c09553',
    'surface-container-high': '#ffffff',
    'surface-container-highest': '#f5f5f5',
    'surface-bright': '#ebebeb',
    'primary-light': '#33aadd',
    'ghost-border': '#e5e5e5',
    'warning': '#bf8803',
    'warning-bg': 'rgba(191, 136, 3, 0.10)',
    'info': '#316bcd',
    'info-bg': 'rgba(49, 107, 205, 0.10)',
    'success': '#388a34',
    // Unity semantics, derived from this theme's own warning / info /
    // accent so no new palette decisions are made on its behalf. Inspector is
    // the RAIL colour, not a text colour — see unityide-dark for why.
    'unity-lifecycle': '#bf8803',
    'unity-engine-type': '#316bcd',
    'unity-inspector': '#007acc',
    'unity-inspector-rail': 'rgba(0, 122, 204, 0.06)',
    'modal-backdrop': 'rgba(0, 0, 0, 0.18)',
    'modal-shadow': '0 8px 24px rgba(0, 0, 0, 0.16)',
    'scrollbar-thumb': 'rgba(0, 0, 0, 0.16)',
    'scrollbar-thumb-hover': 'rgba(0, 0, 0, 0.32)',
    'focus-ring': 'rgba(0, 122, 204, 0.55)',
    'button-primary-bg': '#0e639c',
    'button-primary-text': '#ffffff',
    'button-primary-hover': '#1177bb',
    'button-danger-bg': '#c74e39',
    'button-danger-text': '#ffffff',
    'avatar-gradient-start': '#4a9eff',
    'avatar-gradient-end': '#6366f1',
    'avatar-text': '#ffffff',
  },
  monaco: {
    base: 'vs',
    inherit: true,
    rules: [
      // --- Original 16 rules ---
      { token: 'comment', foreground: '008000' },
      { token: 'keyword', foreground: '0000FF' },
      { token: 'string', foreground: 'A31515' },
      { token: 'number', foreground: '098658' },
      { token: 'type', foreground: '267F99' },
      { token: 'function', foreground: '795E26' },
      { token: 'variable', foreground: '001080' },
      { token: 'constant', foreground: '0070C1' },
      { token: 'parameter', foreground: '001080' },
      { token: 'property', foreground: '001080' },
      { token: 'tag', foreground: '800000' },
      { token: 'attribute.name', foreground: 'FF0000' },
      { token: 'attribute.value', foreground: '0451A5' },
      { token: 'delimiter', foreground: '000000' },
      { token: 'operator', foreground: '000000' },
      { token: 'regexp', foreground: '811F3F' },

      // --- Keywords & Storage ---
      { token: 'keyword.control', foreground: 'AF00DB' },
      { token: 'keyword.operator.new', foreground: '0000FF' },
      { token: 'keyword.operator.expression', foreground: '0000FF' },
      { token: 'storage', foreground: '0000FF' },
      { token: 'storage.type', foreground: '0000FF' },
      { token: 'storage.modifier', foreground: '0000FF' },

      // --- Variables & Constants ---
      { token: 'variable.language', foreground: '0000FF' },
      { token: 'variable.other.constant', foreground: '0070C1' },
      { token: 'constant.language', foreground: '0000FF' },

      // --- Entities & Support ---
      { token: 'entity.name.function', foreground: '795E26' },
      { token: 'entity.name.class', foreground: '267F99' },
      { token: 'entity.name.type', foreground: '267F99' },
      { token: 'support.function', foreground: '795E26' },
      { token: 'support.class', foreground: '267F99' },
      { token: 'support.type', foreground: '267F99' },

      // --- JSX/TSX ---
      { token: 'entity.name.tag', foreground: '800000' },
      { token: 'support.class.component', foreground: '267F99' },

      // --- Punctuation & Delimiters ---
      { token: 'meta.brace.round', foreground: '000000' },
      { token: 'meta.brace.square', foreground: '000000' },
      { token: 'meta.brace.curly', foreground: '000000' },
      { token: 'punctuation.separator', foreground: '000000' },
      { token: 'string.template', foreground: 'A31515' },
      { token: 'punctuation.definition.template-expression', foreground: '0000FF' },

      // --- Decorators ---
      { token: 'meta.decorator', foreground: '795E26' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editorCursor.foreground': '#000000',
      'editor.lineHighlightBackground': '#f5f5f5',
      'editor.selectionBackground': '#add6ff',
      'editorLineNumber.foreground': '#237893',
      'editorLineNumber.activeForeground': '#0b216f',
      'editorIndentGuide.background': '#d3d4d5',
      'editorWidget.background': '#f3f3f3',
      'editorWidget.border': '#c8c8c8',
    },
  },
  terminal: {
    background: '#ffffff',
    foreground: '#333333',
    cursor: '#333333',
    cursorAccent: '#ffffff',
    selectionBackground: '#add6ff',
    black: '#000000',
    red: '#cd3131',
    green: '#00bc00',
    yellow: '#949800',
    blue: '#0451a5',
    magenta: '#bc05bc',
    cyan: '#0598bc',
    white: '#555555',
    brightBlack: '#666666',
    brightRed: '#cd3131',
    brightGreen: '#14ce14',
    brightYellow: '#b5ba00',
    brightBlue: '#0451a5',
    brightMagenta: '#bc05bc',
    brightCyan: '#0598bc',
    brightWhite: '#a5a5a5',
  },
};

export default lightPlus;
