import type { ThemeDefinition } from '../types';

const monokai: ThemeDefinition = {
  id: 'monokai',
  name: 'Monokai',
  type: 'dark',
  ui: {
    'bg-primary': '#272822',
    'bg-sidebar': '#21222c',
    'bg-titlebar': '#1e1f29',
    'bg-tab-active': '#272822',
    'bg-tab-inactive': '#21222c',
    'bg-statusbar': '#414339',
    'bg-activity-bar': '#1e1f29',
    'bg-breadcrumbs': '#272822',
    'bg-input': '#3e3d32',
    'text-primary': '#f8f8f2',
    'text-secondary': '#75715e',
    'text-active': '#ffffff',
    'text-breadcrumb': '#a0a0a0',
    'text-breadcrumb-active': '#f8f8f2',
    'text-on-dark': '#f8f8f2',
    // on #414339 dark olive
    'statusbar-fg': '#f8f8f2',
    'border': '#3b3a32',
    'accent': '#a6e22e',
    'accent-secondary': '#f92672',
    // AI composer mode accents (CONTENT class).
    'mode-ask': '#66d9ef',
    'mode-agent': '#a6e22e',
    'mode-plan': '#fd971f',
    'hover': '#3e3d32',
    'selected': '#49483e',
    'git-modified': '#e6db74',
    'git-added': '#a6e22e',
    'git-deleted': '#f92672',
    'git-untracked': '#a6e22e',
    'badge-bg': 'rgba(255, 255, 255, 0.1)',
    'hover-overlay': 'rgba(255, 255, 255, 0.08)',
    'statusbar-hover': 'rgba(255, 255, 255, 0.12)',
    'error-bg': 'rgba(249, 38, 114, 0.15)',
    'error-border': '#f92672',
    'error-text': '#f92672',
    'editor-error-btn': '#a6e22e',
    'editor-error-btn-hover': '#b6f234',
    'folder-icon': '#e6db74',
    'surface-container-high': '#3e3d32',
    'surface-container-highest': '#484840',
    'surface-bright': '#52514a',
    'primary-light': '#c4f05e',
    'ghost-border': '#3b3a32',
    'warning': '#e6db74',
    'warning-bg': 'rgba(230, 219, 116, 0.14)',
    'info': '#66d9ef',
    'info-bg': 'rgba(102, 217, 239, 0.12)',
    'success': '#a6e22e',
    // Unity semantics, derived from this theme's own warning / info /
    // accent so no new palette decisions are made on its behalf. Inspector is
    // the RAIL colour, not a text colour — see unityide-dark for why.
    'unity-lifecycle': '#e6db74',
    'unity-engine-type': '#66d9ef',
    'unity-inspector': '#a6e22e',
    'unity-inspector-rail': 'rgba(166, 226, 46, 0.06)',
    'modal-backdrop': 'rgba(39, 40, 34, 0.65)',
    'modal-shadow': '0 8px 24px rgba(0, 0, 0, 0.55)',
    'scrollbar-thumb': 'rgba(166, 226, 46, 0.20)',
    'scrollbar-thumb-hover': 'rgba(166, 226, 46, 0.45)',
    'focus-ring': 'rgba(166, 226, 46, 0.65)',
    'button-primary-bg': '#a6e22e',
    'button-primary-text': '#272822',
    'button-primary-hover': '#b6f234',
    'button-danger-bg': '#f92672',
    'button-danger-text': '#272822',
    'avatar-gradient-start': '#a6e22e',
    'avatar-gradient-end': '#f92672',
    'avatar-text': '#272822',
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      // --- Original 16 rules ---
      { token: 'comment', foreground: '75715E', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'F92672' },
      { token: 'string', foreground: 'E6DB74' },
      { token: 'number', foreground: 'AE81FF' },
      { token: 'type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'function', foreground: 'A6E22E' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'constant', foreground: 'AE81FF' },
      { token: 'parameter', foreground: 'FD971F', fontStyle: 'italic' },
      { token: 'property', foreground: 'F8F8F2' },
      { token: 'tag', foreground: 'F92672' },
      { token: 'attribute.name', foreground: 'A6E22E' },
      { token: 'attribute.value', foreground: 'E6DB74' },
      { token: 'delimiter', foreground: 'F8F8F2' },
      { token: 'operator', foreground: 'F92672' },
      { token: 'regexp', foreground: 'E6DB74' },

      // --- Keywords & Storage ---
      { token: 'keyword.control', foreground: 'F92672' },
      { token: 'keyword.operator.new', foreground: 'F92672' },
      { token: 'keyword.operator.expression', foreground: 'F92672' },
      { token: 'storage', foreground: 'F92672' },
      { token: 'storage.type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'storage.modifier', foreground: 'F92672' },

      // --- Variables & Constants ---
      { token: 'variable.language', foreground: 'FD971F', fontStyle: 'italic' },
      { token: 'variable.other.constant', foreground: 'AE81FF' },
      { token: 'constant.language', foreground: 'AE81FF' },

      // --- Entities & Support ---
      { token: 'entity.name.function', foreground: 'A6E22E' },
      { token: 'entity.name.class', foreground: 'A6E22E' },
      { token: 'entity.name.type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'support.function', foreground: '66D9EF' },
      { token: 'support.class', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'support.type', foreground: '66D9EF', fontStyle: 'italic' },

      // --- JSX/TSX ---
      { token: 'entity.name.tag', foreground: 'F92672' },
      { token: 'support.class.component', foreground: 'A6E22E' },

      // --- Punctuation & Delimiters ---
      { token: 'meta.brace.round', foreground: 'F8F8F2' },
      { token: 'meta.brace.square', foreground: 'F8F8F2' },
      { token: 'meta.brace.curly', foreground: 'F8F8F2' },
      { token: 'punctuation.separator', foreground: 'F8F8F2' },
      { token: 'string.template', foreground: 'E6DB74' },
      { token: 'punctuation.definition.template-expression', foreground: 'F92672' },

      // --- Decorators ---
      { token: 'meta.decorator', foreground: 'A6E22E' },
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'editorCursor.foreground': '#f8f8f0',
      'editor.lineHighlightBackground': '#3e3d32',
      'editor.selectionBackground': '#49483e',
      'editorLineNumber.foreground': '#90908a',
      'editorLineNumber.activeForeground': '#c2c2bf',
      'editorIndentGuide.background': '#464741',
      'editorWidget.background': '#21222c',
      'editorWidget.border': '#3b3a32',
    },
  },
  terminal: {
    background: '#272822',
    foreground: '#f8f8f2',
    cursor: '#f8f8f0',
    cursorAccent: '#272822',
    selectionBackground: '#49483e',
    black: '#272822',
    red: '#f92672',
    green: '#a6e22e',
    yellow: '#f4bf75',
    blue: '#66d9ef',
    magenta: '#ae81ff',
    cyan: '#a1efe4',
    white: '#f8f8f2',
    brightBlack: '#75715e',
    brightRed: '#f92672',
    brightGreen: '#a6e22e',
    brightYellow: '#f4bf75',
    brightBlue: '#66d9ef',
    brightMagenta: '#ae81ff',
    brightCyan: '#a1efe4',
    brightWhite: '#f9f8f5',
  },
};

export default monokai;
