/** Editor actions supported by migration, help and the command dispatcher. */
export const MONACO_ACTION_LABELS: Record<string, string> = {
  'editor.action.revealDefinition': 'Go to Definition',
  'editor.action.peekDefinition': 'Peek Definition',
  'editor.action.rename': 'Rename Symbol',
  'actions.find': 'Find',
  'editor.action.startFindReplaceAction': 'Replace',
  'editor.action.commentLine': 'Toggle Line Comment',
  'editor.action.blockComment': 'Toggle Block Comment',
  'editor.action.copyLinesDownAction': 'Duplicate Line Down',
  'editor.action.copyLinesUpAction': 'Duplicate Line Up',
  'editor.action.deleteLines': 'Delete Line',
  'editor.action.moveLinesUpAction': 'Move Line Up',
  'editor.action.moveLinesDownAction': 'Move Line Down',
  'editor.action.indentLines': 'Indent Line',
  'editor.action.outdentLines': 'Outdent Line',
  'editor.action.joinLines': 'Join Lines',
  'editor.action.smartSelect.expand': 'Expand Selection',
  'editor.action.smartSelect.shrink': 'Shrink Selection',
  'editor.action.insertCursorAbove': 'Add Cursor Above',
  'editor.action.insertCursorBelow': 'Add Cursor Below',
  'editor.action.addSelectionToNextFindMatch': 'Select Next Occurrence',
  'editor.action.selectHighlights': 'Select All Occurrences',
  'expandLineSelection': 'Select Line',
  'editor.action.jumpToBracket': 'Go to Matching Bracket',
  'editor.fold': 'Fold',
  'editor.unfold': 'Unfold',
  'editor.foldAll': 'Fold All',
  'editor.unfoldAll': 'Unfold All',
  'editor.action.triggerSuggest': 'Show Completions',
  'editor.action.triggerParameterHints': 'Show Parameter Hints',
};
