//! Stable per-install identity, for the first-run ping.
//!
//! The app reports its very first launch to `POST /v1/install`, which is the
//! only signal that distinguishes someone who actually ran UnityIDE from
//! someone who merely clicked a download link. That report needs an id that is
//! stable across launches and unique per machine, and a record of whether it
//! has already been sent.
//!
//! Two properties are load-bearing:
//!
//!  1. **Creation is atomic.** UnityIDE opens one window per project, and two
//!     launching at once would otherwise each mint an id, write it, and report
//!     — inventing an install that never happened. `create_new` is an atomic
//!     test-and-set at the filesystem level, so exactly one writer wins and
//!     the loser reads back the winner's id.
//!  2. **The id is generated by the caller.** The WebView has
//!     `crypto.randomUUID()`; Rust here has no random source without pulling
//!     in a dependency for one string. The candidate is proposed from the
//!     frontend and this module decides whether it is adopted.
//!
//! The file lives in the per-channel config dir (`~/.unityide`, or
//! `~/.unityide-dev`), so a dev build never reports as a production install.

use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

const INSTALL_FILE: &str = "install.json";

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstallRecord {
    pub install_id: String,
    /// Whether the server has already accepted a first-run report for this id.
    #[serde(default)]
    pub reported: bool,
}

fn install_path(dir: &Path) -> PathBuf {
    dir.join(INSTALL_FILE)
}

/// Adopt `candidate` as this machine's install id, or return the one already
/// recorded.
///
/// A corrupt or truncated file is treated as absent and overwritten: the id is
/// only meaningful as a deduplication key, so a fresh one costs at most one
/// duplicate install — whereas refusing to proceed would cost every future
/// report from this machine. The server deduplicates on the id as well, which
/// is what makes that trade acceptable rather than merely convenient.
pub fn claim(dir: &Path, candidate: &str) -> Result<InstallRecord, String> {
    fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    let path = install_path(dir);

    if let Some(record) = read_valid(&path) {
        return Ok(record);
    }

    let record = InstallRecord {
        install_id: candidate.to_string(),
        reported: false,
    };
    let body = serde_json::to_string(&record).map_err(|e| e.to_string())?;

    publish(dir, &path, &body)?;

    // Always report what is actually ON DISK, never the candidate we happened
    // to propose. Whether we won the race is not something this function needs
    // to know, and trusting our own copy is precisely how a losing thread
    // returns an id that no other launch will ever agree with.
    //
    // Because `publish` only makes the file visible with its contents already
    // in it, a record that still fails to parse here is genuinely corrupt
    // rather than half-written, so replacing it cannot clobber a live id.
    if let Some(existing) = read_valid(&path) {
        return Ok(existing);
    }
    fs::write(&path, &body).map_err(|e| e.to_string())?;
    Ok(record)
}

/// Create `path` with `body` if and only if it does not already exist.
/// Returns whether this call is the one that created it.
///
/// The obvious implementation — `create_new` then `write_all` — has a race
/// that matters here: `create_new` publishes an EMPTY file and the contents
/// land a moment later, so a second launch can open it, read nothing, judge it
/// corrupt, and overwrite the winner's id with its own. Two ids means two
/// installs means two ad conversions for one machine.
///
/// Writing the contents to a temporary file first and then hard-linking it
/// into place closes that window: the destination name springs into existence
/// already complete, and `hard_link` fails rather than overwriting when the
/// name is taken.
fn publish(dir: &Path, path: &Path, body: &str) -> Result<bool, String> {
    // The temp name must be unique per CALL, not per process or per instant:
    // two windows launching together can land on the same nanosecond, and
    // sharing a temp file means one thread's contents get linked under the
    // other's name — publishing an id nobody agrees on. A process-wide counter
    // is the part that makes this reliable; the pid keeps two processes apart.
    static SEQ: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
    let seq = SEQ.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let tmp = dir.join(format!("{INSTALL_FILE}.tmp.{}.{seq}", std::process::id()));

    fs::write(&tmp, body).map_err(|e| e.to_string())?;
    let linked = fs::hard_link(&tmp, path);
    let _ = fs::remove_file(&tmp);

    match linked {
        Ok(()) => Ok(true),
        Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => Ok(false),
        // Filesystems without hard links (a FAT32 volume, some network mounts)
        // fall back to the racy-but-functional form. A duplicate install there
        // is a far better outcome than refusing to record one at all — and the
        // server deduplicates on the id regardless.
        Err(_) => match OpenOptions::new().write(true).create_new(true).open(path) {
            Ok(mut file) => {
                file.write_all(body.as_bytes()).map_err(|e| e.to_string())?;
                Ok(true)
            }
            Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => Ok(false),
            Err(err) => Err(err.to_string()),
        },
    }
}

/// A usable record at `path`, or None for absent, unreadable, malformed, or
/// present-but-empty — every one of which means "we do not have an id yet".
fn read_valid(path: &Path) -> Option<InstallRecord> {
    let text = fs::read_to_string(path).ok()?;
    let record = serde_json::from_str::<InstallRecord>(&text).ok()?;
    (!record.install_id.is_empty()).then_some(record)
}

/// Record that the server has accepted this install's first-run report.
///
/// Written only AFTER a successful POST, so a failed report is retried on the
/// next launch rather than silently lost. The cost of the opposite ordering is
/// an install that never appears; the cost of this ordering is at most a
/// duplicate POST, which the server discards.
pub fn mark_reported(dir: &Path) -> Result<(), String> {
    let path = install_path(dir);
    let text = fs::read_to_string(&path).map_err(|e| e.to_string())?;
    let mut record: InstallRecord = serde_json::from_str(&text).map_err(|e| e.to_string())?;
    record.reported = true;
    let body = serde_json::to_string(&record).map_err(|e| e.to_string())?;
    fs::write(&path, body).map_err(|e| e.to_string())
}

// ─── Tauri commands ─────────────────────────────────────────

#[tauri::command]
pub fn install_claim(app: tauri::AppHandle, candidate: String) -> Result<InstallRecord, String> {
    claim(&crate::auth::config_home_dir(&app)?, &candidate)
}

#[tauri::command]
pub fn install_mark_reported(app: tauri::AppHandle) -> Result<(), String> {
    mark_reported(&crate::auth::config_home_dir(&app)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmpdir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("unityide-install-{name}-{:?}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        dir
    }

    #[test]
    fn adopts_the_candidate_on_a_fresh_machine() {
        let dir = tmpdir("fresh");
        let record = claim(&dir, "candidate-1").unwrap();
        assert_eq!(record.install_id, "candidate-1");
        assert!(!record.reported);
    }

    #[test]
    fn keeps_the_first_id_on_later_launches() {
        let dir = tmpdir("stable");
        claim(&dir, "first").unwrap();
        let second = claim(&dir, "second").unwrap();
        assert_eq!(
            second.install_id, "first",
            "a second launch proposing a new id must not replace the recorded one"
        );
    }

    #[test]
    fn remembers_that_the_report_was_sent() {
        let dir = tmpdir("reported");
        claim(&dir, "id-1").unwrap();
        mark_reported(&dir).unwrap();

        let reread = claim(&dir, "ignored").unwrap();
        assert!(reread.reported, "a reported install must not report again");
        assert_eq!(reread.install_id, "id-1");
    }

    /// The whole point of `create_new`: two windows launching together must
    /// agree on one id, or the server sees two installs where there was one.
    #[test]
    fn concurrent_claims_agree_on_a_single_id() {
        let dir = tmpdir("concurrent");
        fs::create_dir_all(&dir).unwrap();

        let handles: Vec<_> = (0..8)
            .map(|i| {
                let dir = dir.clone();
                std::thread::spawn(move || claim(&dir, &format!("candidate-{i}")).unwrap().install_id)
            })
            .collect();

        let ids: Vec<String> = handles.into_iter().map(|h| h.join().unwrap()).collect();
        let first = &ids[0];
        assert!(
            ids.iter().all(|id| id == first),
            "all concurrent claims must resolve to one id, got {ids:?}"
        );
    }

    #[test]
    fn replaces_a_corrupt_record_rather_than_failing_forever() {
        let dir = tmpdir("corrupt");
        fs::create_dir_all(&dir).unwrap();
        fs::write(install_path(&dir), "{ this is not json").unwrap();

        let record = claim(&dir, "recovered").unwrap();
        assert_eq!(record.install_id, "recovered");
    }

    #[test]
    fn treats_an_empty_id_as_absent() {
        let dir = tmpdir("empty-id");
        fs::create_dir_all(&dir).unwrap();
        fs::write(install_path(&dir), r#"{"installId":"","reported":false}"#).unwrap();

        assert_eq!(claim(&dir, "replacement").unwrap().install_id, "replacement");
    }
}
